# VQLS Solver

In [7]:
import numpy as np
import scipy.sparse as sp
np.random.seed(20)

In [22]:
A = sp.random(4,4,density = 0.25)
A = A + A.T
A = A.todense()
A

matrix([[0.        , 0.73688738, 0.        , 0.98942514],
        [0.73688738, 0.        , 0.79096501, 0.        ],
        [0.        , 0.79096501, 0.        , 0.86638985],
        [0.98942514, 0.        , 0.86638985, 0.        ]])

In [23]:
b = np.random.rand(4)


In [35]:
from vqls_prototype.matrix_decomposition import PauliDecomposition, SymmetricDecomposition
pd = PauliDecomposition(A)

ImportError: cannot import name 'MatrixDecomposition' from 'vqls_prototype.matrix_decomposition' (/home/nico/QuantumApplicationLab/vqls-prototype/vqls_prototype/matrix_decomposition/__init__.py)

In [39]:
decomposition = {
"pauli": PauliDecomposition,
"symmetric": SymmetricDecomposition,
}
isinstance(pd, (PauliDecomposition,SymmetricDecomposition))

True

In [32]:
pd.recompose()

array([[0.        +0.j, 0.73688738+0.j, 0.        +0.j, 0.98942514+0.j],
       [0.73688738+0.j, 0.        +0.j, 0.79096501+0.j, 0.        +0.j],
       [0.        +0.j, 0.79096501+0.j, 0.        +0.j, 0.86638985+0.j],
       [0.98942514+0.j, 0.        +0.j, 0.86638985+0.j, 0.        +0.j]])

## Classical Solution

The solution of such a small system can be obtained by a least square as implemented in numpy

In [5]:
npsol = np.linalg.solve(A,b)
npsol = np.asarray(npsol).flatten()
print(npsol)

[-0.03707238  0.63032045 -0.37186951  0.09258987]


## 3. Solving the system

We will use here the `VQLS` to be able to run that code locally. 

In [14]:
from vqls_prototype import VQLS
from qiskit.primitives import Estimator
from qiskit.circuit.library import RealAmplitudes 
from qiskit_algorithms.optimizers import CG
qc = RealAmplitudes(2, reps=3, entanglement='full')
estimator = Estimator()

vqls = VQLS(
    estimator,
    qc,
    CG(),
    options={"matrix_decomposition":"pauli"}
)
res = vqls.solve(A,b)

100%|██████████| 16/16 [00:00<00:00, 1387.55it/s]
